config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    get "/", to: "dashboard#index"
    get "/users", to: "users#index"
    get "/users/:id", to: "users#show"
    get "/merchants", to: "merchants#index"
    get "/merchants/:merchant_id", to: "merchants#show"
    patch "/merchants/:merchant_id", to: "merchants#update"
    patch "/order/:id", to: "order#ship", as: :order_ship
    namespace :merchant do
      get ":id/items", to: "items#index", as: :items
      get ":id/items/:item_id", to: "items#show", as: :item_show
      patch ":id/items/:item_id", to: "items#update", as: :item_update
      delete "/items/:id", to: "items#destroy", as: :item_destroy
      get ":id/orders/:order_id", to: "orders#show", as: :order_show
    end
  end

  namespace :merchant do
    get "/", to: "dashboard#index"
    get "/items", to: "items#index"
    get "/items/new", to: "items#new"
    post "/items", to: "items#create"
    get "/items/:id", to: "items#show", as: :item_show
    get "/items/:id/edit", to: "items#edit", as: :item_edit
    patch "/items/:id", to: "items#update", as: :item_update
    delete "/items/:id", to: "items#destroy", as: :item_destroy
    get "/orders/:id", to: "orders#show", as: :order_show
    patch "/itemorders/:id", to: "item_orders#update", as: :item_order_update
    get "/bulk_discounts", to: "bulk_discounts#index", as: :bulk_discounts
    get "/bulk_discounts/new", to: "bulk_discounts#new", as: :bulk_discounts_new
    post "/bulk_discounts/new", to: "bulk_discounts#create", as: :bulk_discounts_create
    get "/bulk_discounts/:id", to: "bulk_discounts#show", as: :bulk_discounts_show
    get "bulk_discounts/:id/edit", to: "bulk_discounts#edit", as: :bulk_discounts_edit
    patch "bulk_discounts/:id/edit", to: "bulk_discounts#update", as: :bulk_discounts_update
    delete "bulk_discounts/:id", to: "bulk_discounts#destroy", as: :bulk_discounts_destroy
  end

  get "/merchants", to: "merchants#index"
  get "/merchants/new", to: "merchants#new"
  get "/merchants/:id", to: "merchants#show"
  post "/merchants", to: "merchants#create"
  get "/merchants/:id/edit", to: "merchants#edit"
  patch "/merchants/:id", to: "merchants#update"
  delete "/merchants/:id", to: "merchants#destroy"
  get "/merchants/:merchant_id/items", to: "items#index"
  get "/merchants/:merchant_id/items/new", to: "items#new"
  post "/merchants/:merchant_id/items", to: "items#create"

  get "/items", to: "items#index"
  get "/items/:id", to: "items#show", as: :item_show


  get "/items/:item_id/reviews/new", to: "reviews#new"
  post "/items/:item_id/reviews", to: "reviews#create"

  get "/reviews/:id/edit", to: "reviews#edit"
  patch "/reviews/:id", to: "reviews#update"
  delete "/reviews/:id", to: "reviews#destroy"

  post "/cart/:item_id", to: "cart#add_item"
  get "/cart", to: "cart#show"
  patch "/cart/:item_id", to: "cart#update", as: :update_cart
  delete "/cart", to: "cart#empty"
  delete "/cart/:item_id", to: "cart#remove_item"

  get "/orders/new", to: "orders#new"
  post "/orders", to: "orders#create"
  get "/orders/:id", to: "orders#show", as: :order_show
  patch "/orders/:id", to: "orders#cancel", as: :order_cancel


  get "/register", to: "users#new"


  post "/profile", to: "users#create"
  get "/profile", to: "users#show"
  get "/profile/edit", to: 'users#edit'
  patch "/profile/update", to: 'users#update'
  get "/profile/change_password", to: "users#change_password"
  patch "/profile/update_password", to: "users#update_password"
  get "profile/orders", to: "user/orders#index", as: :user_orders
  get "profile/orders/:order_id", to: "user/orders#show", as: :user_order_show
end

app/views/partials/_item_index.html.erb
<section class="grid-item" id='item-<%=item.id%>'>
  <h2> <%=link_to item.name, "/items/#{item.id}" %> </h2>
  <h4> <%=link_to "Edit #{item.name}", merchant_item_edit_path(item) %> </h4>
  <p>Sold by: <%=link_to item.merchant.name, "/merchants/#{item.merchant.id}" %></p>
  <%=link_to image_tag(item.image), "/items/#{item.id}", id: "item-image-#{item.id}" %>
  <p> <%= item.description %> </p>
  <p>Price: <%=number_to_currency(item.price) %> </p>
  <p>Inventory: <%= item.inventory %> </p>
  <% if item.active? %>
    <p>Active</p>
    <%= link_to "Deactivate", merchant_item_update_path(item, active?: false), method: :patch if current_user.merchant?%>
    <%= link_to "Deactivate", admin_merchant_item_update_path(@merchant, item, active?: false), method: :patch if current_user.admin?%>
  <% else %>
    <p>Inactive</p>
    <%= link_to "Activate", merchant_item_update_path(item, active?: true), method: :patch if current_user.merchant?%>
    <%= link_to "Activate", admin_merchant_item_update_path(@merchant, item, active?: true), method: :patch if current_user.admin?%>
  <% end %>
    <%= link_to "Delete", path, method: :delete if item.deletable?%>
</section>

app/views/partials/_merchants_show.html.erb
<h1><%=@merchant.name%> Dashboard</h1>
<h4>Located at</h4>
<p><%=@merchant.address%>
<%=@merchant.city%>
<%=@merchant.state%>
<%=@merchant.zip%></p>
<p><%= link_to "My Discounts", merchant_bulk_discounts_path if current_merchant? %></p><br>
<p><%= link_to "New Discount", merchant_bulk_discounts_new_path if current_merchant? %></p><br>
<p><%= link_to "View My Items", merchant_items_path if current_merchant?%> </p><br>
<p><%= link_to "View My Items", "/admin/merchant/#{@merchant.id}/items" if current_admin?%></p><br>

<h4>My Pending Orders</h4>
<% @merchant.pending_orders.each do |order| %>
  <p>Order # <%= link_to "#{order.id}", "/merchant/orders/#{order.id}"%></p>
  <p>Created at <%=order.created_at%></p>
  <p>Number of My Items: <%=order.number_of_items_for_merchant(@merchant.id)%></p>
  <p>Value of My Items: <%=number_to_currency(order.total_cost_for_merchant(@merchant.id))%></p>
<%end%>