config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    get "/", to: "dashboard#index"
    get "/users", to: "users#index"
    get "/users/:id", to: "users#show"
    get "/merchants", to: "merchants#index"
    get "/merchants/:merchant_id", to: "merchants#show"
    patch "/merchants/:merchant_id", to: "merchants#update"
    patch "/order/:id", to: "order#ship", as: :order_ship
    namespace :merchant do
      get ":id/items", to: "items#index", as: :items
      get ":id/items/:item_id", to: "items#show", as: :item_show
      patch ":id/items/:item_id", to: "items#update", as: :item_update
      delete "/items/:id", to: "items#destroy", as: :item_destroy
      get ":id/orders/:order_id", to: "orders#show", as: :order_show
    end
  end

  namespace :merchant do
    get "/", to: "dashboard#index"
    get "/items", to: "items#index"
    get "/items/new", to: "items#new"
    post "/items", to: "items#create"
    get "/items/:id", to: "items#show", as: :item_show
    get "/items/:id/edit", to: "items#edit", as: :item_edit
    patch "/items/:id", to: "items#update", as: :item_update
    delete "/items/:id", to: "items#destroy", as: :item_destroy
    get "/orders/:id", to: "orders#show", as: :order_show
    patch "/itemorders/:id", to: "item_orders#update", as: :item_order_update
    get "/bulk_discounts", to: "bulk_discounts#index", as: :bulk_discounts
    get "/bulk_discounts/new", to: "bulk_discounts#new", as: :bulk_discounts_new
    post "/bulk_discounts/new", to: "bulk_discounts#create", as: :bulk_discounts_create
    get "/bulk_discounts/:id", to: "bulk_discounts#show", as: :bulk_discounts_show
    get "bulk_discounts/:id/edit", to: "bulk_discounts#edit", as: :bulk_discounts_edit
    patch "bulk_discounts/:id/edit", to: "bulk_discounts#update", as: :bulk_discounts_update
    delete "bulk_discounts/:id", to: "bulk_discounts#destroy", as: :bulk_discounts_destroy
  end

  get "/merchants", to: "merchants#index"
  get "/merchants/new", to: "merchants#new"
  get "/merchants/:id", to: "merchants#show"
  post "/merchants", to: "merchants#create"
  get "/merchants/:id/edit", to: "merchants#edit"
  patch "/merchants/:id", to: "merchants#update"
  delete "/merchants/:id", to: "merchants#destroy"
  get "/merchants/:merchant_id/items", to: "items#index"
  get "/merchants/:merchant_id/items/new", to: "items#new"
  post "/merchants/:merchant_id/items", to: "items#create"

  get "/items", to: "items#index"
  get "/items/:id", to: "items#show", as: :item_show


  get "/items/:item_id/reviews/new", to: "reviews#new"
  post "/items/:item_id/reviews", to: "reviews#create"

  get "/reviews/:id/edit", to: "reviews#edit"
  patch "/reviews/:id", to: "reviews#update"
  delete "/reviews/:id", to: "reviews#destroy"

  post "/cart/:item_id", to: "cart#add_item"
  get "/cart", to: "cart#show"
  patch "/cart/:item_id", to: "cart#update", as: :update_cart
  delete "/cart", to: "cart#empty"
  delete "/cart/:item_id", to: "cart#remove_item"

  get "/orders/new", to: "orders#new"
  post "/orders", to: "orders#create"
  get "/orders/:id", to: "orders#show", as: :order_show
  patch "/orders/:id", to: "orders#cancel", as: :order_cancel


  get "/register", to: "users#new"


  post "/profile", to: "users#create"
  get "/profile", to: "users#show"
  get "/profile/edit", to: 'users#edit'
  patch "/profile/update", to: 'users#update'
  get "/profile/change_password", to: "users#change_password"
  patch "/profile/update_password", to: "users#update_password"
  get "profile/orders", to: "user/orders#index", as: :user_orders
  get "profile/orders/:order_id", to: "user/orders#show", as: :user_order_show
end

app/models/item.rb
class Item <ApplicationRecord
  before_save :set_image
  belongs_to :merchant
  has_many :reviews, dependent: :destroy
  has_many :item_orders
  has_many :orders, through: :item_orders
  has_many :bulk_discounts, dependent: :destroy

  validates_presence_of :name,
                        :description,
                        :price,
                        :inventory
  validates_inclusion_of :active?, :in => [true, false]
  validates_numericality_of :price, greater_than: 0, only_integer: true
  validates_numericality_of :inventory, greater_than_or_equal_to: 0, only_integer: true

  def average_review
    reviews.average(:rating)
  end

  def sorted_reviews(limit, order)
    reviews.order(rating: order).limit(limit)
  end

  def no_orders?
    item_orders.empty?
  end

  def activate
    update(active?: true)
  end

  def deactivate
    update(active?: false)
  end

  def self.most_popular(num_items_to_show)
    Item.joins(:item_orders)
        .select('items.*, sum(item_orders.quantity)')
        .group(:id)
        .order("sum(item_orders.quantity) DESC")
        .limit(num_items_to_show)
  end

  def self.least_popular(num_items_to_show)
    Item.joins(:item_orders)
        .select('items.*, sum(item_orders.quantity)')
        .group(:id)
        .order("sum(item_orders.quantity) ASC")
        .limit(num_items_to_show)
  end

  def deletable?
    !orders.any?
  end

  def set_image
    self.image = "https://upload.wikimedia.org/wikipedia/commons/1/15/No_image_available_600_x_450.svg" if self.image.blank?
  end

  def best_discount_percentage(quantity)
    return 0 unless bulk_discount = bulk_discounts.where('quantity <= ?', quantity).order(discount: :desc).first
    bulk_discount.discount.to_f / 100
  end

  def price_after_discounts(quantity)
    price - (price * best_discount_percentage(quantity))
  end

  def has_discounts?
    bulk_discounts.any?
  end
end

app/models/merchant.rb
class Merchant <ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :item_orders, through: :items
  has_many :users
  has_many :bulk_discounts, through: :items
  

  validates_presence_of :name, :address, :city, :state, :zip


  def no_orders?
    item_orders.empty?
  end

  def item_count
    items.count
  end

  def average_item_price
    items.average(:price)
  end

  def distinct_cities
    item_orders.distinct.joins(:order).pluck(:city)
  end

  def pending_orders
    Order.joins(:items).distinct.where(items: {merchant_id: id}).where(status: 'pending')
  end

  def disable
    update(active?: false)
    items.each { |item| item.deactivate }
  end

  def enable
    update(active?: true)
    items.each { |item| item.activate }
  end

end

app/controllers/admin/merchant/items_controller.rb
class Admin::Merchant::ItemsController < Admin::BaseController

  def index
    @merchant = Merchant.find(params[:id])
  end

  def update
    merchant = Merchant.find(params[:id])
    item = Item.find(params[:item_id])
    if item.update(item_params)
      flash[:success] = "Item #{item.id} is " + item_active_message(item.active?)
    end
    redirect_to admin_merchant_items_path
  end

  def destroy
    item = Item.find(params[:id])
    Review.where(item_id: item.id).destroy_all
    item.destroy
    redirect_to "/items"
  end

  def item_params
    params.permit(:name,:description,:price,:inventory,:image, :active?)
  end

end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < Admin::BaseController
  def index
    @merchants = Merchant.all
  end

  def update
    merchant = Merchant.find(params[:merchant_id])
    if merchant.active?
      merchant.disable
      flash[:disabled] = "#{merchant.name} has been disabled."
    else
      merchant.enable
      flash[:enabled] = "#{merchant.name} has been enabled."
    end
    redirect_to "/admin/merchants"
  end

  def show
    @merchant = Merchant.find(params[:merchant_id])
  end
end

app/controllers/items_controller.rb
class ItemsController<ApplicationController

  def index
    if params[:merchant_id]
      @merchant = Merchant.find(params[:merchant_id])
      @items = @merchant.items
    else
      @items = Item.where(active?: true)
    end
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/merchant/base_controller.rb
class Merchant::BaseController < ApplicationController
  before_action :require_merchant
  
  def index
    @merchant = Merchant.find(current_user.merchant.id)
  end

private

  def require_merchant
     render file: "/public/404" unless current_merchant?
  end

end

app/controllers/merchant/bulk_discounts_controller.rb
class Merchant::BulkDiscountsController < Merchant::BaseController

  def new
    @merchant = Merchant.find(current_user.merchant.id)
  end

  def create
    @merchant = Merchant.find(current_user.merchant.id)
    bulk_discount = BulkDiscount.new(discounts_params)
    if bulk_discount.save
      flash[:success] = "#{bulk_discount.discount}% discount on #{bulk_discount.item.name} Created"
      redirect_to merchant_bulk_discounts_path
    else
      flash.now[:error] = bulk_discount.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @bulk_discount = BulkDiscount.find(params[:id])
  end

  def edit
    @bulk_discount = BulkDiscount.find(params[:id])
  end

  def update
    @bulk_discount = BulkDiscount.find(params[:id])
    if @bulk_discount.update(discounts_params)
      flash[:success] = "#{@bulk_discount.discount}% discount on #{@bulk_discount.item.name} Updated"
      redirect_to merchant_bulk_discounts_path
    else
      flash[:error] = @bulk_discount.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    bulk_discount = BulkDiscount.find(params[:id])
    if bulk_discount.destroy
      flash[:success] = "#{bulk_discount.discount}% discount on #{bulk_discount.item.name} Deleted"
    end
    redirect_to merchant_bulk_discounts_path
  end

  private

  def discounts_params
    params.permit(:quantity, :discount, :item_id)
  end
end

app/controllers/merchant/dashboard_controller.rb
class Merchant::DashboardController < Merchant::BaseController

end

app/controllers/merchant/item_orders_controller.rb
class Merchant::ItemOrdersController < Merchant::BaseController

  def update
    item_order = ItemOrder.find(params[:id])
    if item_order.fulfill
      flash[:success] = "#{item_order.item.name} has been fulfilled"
    end
    redirect_to merchant_order_show_path(item_order.order)
  end
  
end

app/controllers/merchant/items_controller.rb
class Merchant::ItemsController < Merchant::BaseController

  def new
    @item = Item.new()
  end

  def show
    @merchant = Merchant.find(current_user.merchant.id)
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    merchant = Merchant.find(current_user.merchant.id)
    @item = merchant.items.new(item_params)
    if @item.save
      flash[:success] = "#{@item.name} has been created."
      flash[:notice] = "Item #{@item.name} is " + item_active_message(@item.active?)
      redirect_to merchant_items_path
    else
      flash.now[:error] = @item.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "Item #{@item.id} is " + item_active_message(@item.active?)
      redirect_to merchant_items_path
    else
      flash[:error] = @item.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    Review.where(item_id: item.id).destroy_all
    if item.destroy
      flash[:success] = "Item #{item.id} has been deleted"
    end
    redirect_to merchant_items_path
  end

  private

  def item_params
    params.permit(:name,:description,:price,:inventory,:image,:active?)
  end
end

app/controllers/merchant/orders_controller.rb
class Merchant::OrdersController < Merchant::BaseController

  def show
    @order = Order.find(order_params[:id])
  end

  private

  def order_params
    params.permit(:id, :name,:description,:price,:inventory,:image, :status)
  end
end

app/controllers/merchants_controller.rb
class MerchantsController <ApplicationController

  def index
    @merchants = Merchant.all
  end

  def show
    @merchant = Merchant.find(params[:id])
  end

  def new
  end

  def create
    merchant = Merchant.create(merchant_params)
    if merchant.save
      redirect_to merchants_path
    else
      flash.now[:error] = merchant.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @merchant = Merchant.find(params[:id])
  end

  def update
    @merchant = Merchant.find(params[:id])
    @merchant.update(merchant_params)
    if @merchant.save
      redirect_to "/merchants/#{@merchant.id}"
    else
      flash.now[:error] = @merchant.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    Merchant.destroy(params[:id])
    redirect_to '/merchants'
  end

  private

  def merchant_params
    params.permit(:name,:address,:city,:state,:zip)
  end

end

app/views/merchant/items/edit.html.erb
<h1>Edit <%=link_to @item.name, "/items/#{@item.id}" %></h1>

<center>
  <%= form_tag merchant_item_update_path(@item), method: :patch  do %>
    <%= label_tag :name %>
    <%= text_field_tag :name, "#{@item.name}"%>

    <%= label_tag :description %>
    <%= text_field_tag :description, "#{@item.description}" %>

    <%= label_tag :price %>
    <%= text_field_tag :price, "#{@item.price}" %>

    <%= label_tag :image %>
    <%= text_field_tag :image, "#{@item.image}" %>

    <%= label_tag :inventory %>
    <%= text_field_tag :inventory, "#{@item.inventory}" %>

    <%= submit_tag 'Update Item' %>
  <% end %>
</center>

app/views/merchant/items/index.html.erb
<section class="grid-container item-list">
  <% @merchant.items.each do |item| %>
    <%= render partial: '/partials/item_index', locals: {item: item, path: merchant_item_destroy_path(item) } %>
  <% end %>
</section>
<%= link_to "New Item", merchant_items_new_path %>

app/views/merchant/items/new.html.erb
<%= form_tag "/merchant/items", method: :post do %>
	<%= label_tag :name %>
	<%= text_field_tag :name, "#{@item.name}" %>

  <%= label_tag :price %>
  <%= text_field_tag :price, "#{@item.price}" %>

	<%= label_tag :description %>
	<%= text_field_tag :description, "#{@item.description}" %>

	<%= label_tag :image %>
	<%= text_field_tag :image, ("#{@item.image}" if params[:image] != nil) %>

  <%= label_tag :inventory %>
  <%= text_field_tag :inventory, "#{@item.inventory}" %>

  <%= submit_tag 'Create Item' %>
<% end%>

app/views/merchant/items/show.html.erb
<h1><%= link_to @item.name, "/items/#{@item.id}" %></h1>
<p align="center">Sold by: <%=link_to @item.merchant.name, "/merchants/#{@item.merchant.id}" %> </p>
<section align = "center" id = "average-rating">
  <p>Average Rating: <%= @item.average_review %></p>
</section>
<center>
  <section class = "item-show-grid">
    <section class = "item-show-item">
      <img src= <%= @item.image %>>
    </section>
    <section style="text-align:left" class = "item-show-item">
      <p><%= @item.description %></p>
      <p>Price: <%= number_to_currency(@item.price )%> </p>
      <p>Inventory: <%= @item.inventory %> </p>
      <% if @item.active? %>
        <p style= "color:green">Active</p>
      <% else %>
        <p style= "color:red">Inactive</p>
      <% end %>
      <p><%= link_to "Edit Item", merchant_item_update_path(@item) %></p>
      <p><%= link_to "Delete Item", merchant_item_destroy_path(@item), method: :delete if @item.no_orders?%></p>
      <%= link_to "Add Review", "/items/#{@item.id}/reviews/new" %>
      <%= button_to "Add To Cart", "/cart/#{@item.id}", method: :post %>
    </section>
  </section>
</center>
<center>
<section class = "review-stats">
  <%if @item.reviews.empty? %>
    <h3>This item has not yet been reviewed.</h3>
  <% else %>
    <section class = "top-three-reviews">
      <h2>Top 3 Reviews</h2>
      <% @item.sorted_reviews(3, :desc).each do |review| %>
        <h3><%= "#{review.rating}-#{review.title}" %></h3>
      <% end %>
    </section>
    <section class = "bottom-three-reviews">
      <h2>Bottom 3 Reviews</h2>
      <% @item.sorted_reviews(3, :asc).each do |review| %>
        <h3><%= "#{review.rating}-#{review.title}" %></h3>
      <% end %>
    </section>
  </section>
  <section class = "list-reviews">
    <h2>All Reviews</h2>
    <% @item.reviews.each do |review| %>
      <section id= 'review-<%=review.id%>'>
        <%= review.title %>
        <%= review.content %>
        Rating: <%= review.rating %>/5
        <%= link_to "Edit", "/reviews/#{review.id}/edit" %>
        <%= link_to "Delete", "/reviews/#{review.id}", method: :delete %>
      </section>
    <% end %>
  <% end %>
</section>
</center>